### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by abenezer-addisu** [mailsg/Awesome-Books#4] opened 2023-05-04 07:32 UTC
Hi @mailsg 🖐
I'm Abenezer your morning session partner

Good job so far! 🎉

Highlights
✔Good job overall following the template design 
✔Correct GitHub Flow 

But there are some issues that you still need to work on but you are almost there!♻️

- [ ]  Fix the bottom margin property in the footer 

Cheers and Happy coding!

**Comment by mailsg** [comment] 2023-05-05 12:19
Thanks for the review @abenezer-addisu , the issue is fixed now.

**Closed as completed by mailsg** 2023-05-05 12:19 UTC
